apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - app
                      - monitoring

#      nodeSelector:
#        workload: app

#      tolerations:
#        - key: dedicated
#          operator: Equal
#          value: training
#          effect: NoSchedule
      containers:
        - name: nginx
          image: image: ghcr.io/abaprogramm/nginx-app:initial
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
